# Generated by Django 2.0.3 on 2018-03-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id_application', models.AutoField(primary_key=True, serialize=False)),
                ('datedeb', models.DateField()),
                ('datefin', models.DateField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_language', models.CharField(blank=True, max_length=30, null=True)),
                ('experience_years', models.IntegerField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('Adress', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('teamwork', models.IntegerField(blank=True, null=True)),
                ('last_company', models.CharField(blank=True, max_length=50, null=True)),
                ('past_university', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_expectation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Application')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_abbreviation', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=80)),
                ('university_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalView',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chatbot.Person')),
                ('desired_skills', models.IntegerField()),
                ('other_skills', models.IntegerField()),
                ('university', models.IntegerField()),
                ('language', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('company', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('teamwork', models.IntegerField()),
                ('final_rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='personskills',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Person'),
        ),
        migrations.AddField(
            model_name='personlanguages',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='app_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Application'),
        ),
        migrations.AddField(
            model_name='application',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Company'),
        ),
    ]
