# Generated by Django 2.0.4 on 2018-05-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
